version: '3'
services:

  apache-oidc:
    build: ./apache-oidc
    depends_on:
      - "java-app"
      - "python-app"
      - "keycloak"
    networks:
      - public-network
      - private-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      OIDC_PROVIDER_METADATA_URL: http://localhost/auth/realms/easy-sso/.well-known/openid-configuration
      OIDC_CLIENT_ID: apache-oidc
      OIDC_CLIENT_SECRET: GhnjZRoQ59gN0dNGmDqJThrbenxohknx
      OIDC_CRYPTO_PASSPHRASE: theMegaPassPhraseOfTheDeath

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - private-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HOSTNAME: localhost
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    command: start-dev --import-realm --proxy edge --hostname-path=/auth

  python-app:
    build: ./python-app
    depends_on:
      - "keycloak"
    networks:
      - private-network

  java-app:
    build: ./java-app
    depends_on:
      - "keycloak"
    networks:
      - private-network

networks:
  public-network:
  private-network:

volumes:
  # Volume to store keycloak config
  pgdata:

